version: "3.8"

services: 
  nuxt-app:
    build: ./website
    ports:
      - '3000:3000'
    depends_on:
      - express
    env_file:
      - .env
    environment:
      - NUXT_API_URL=http://express:3030/
    restart: unless-stopped 

  express:
    build: ./server
    ports:
      - '3030:3030'
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/MindForge?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLERK_PUBLISHABLE_KEY=${NUXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${NUXT_CLERK_SECRET_KEY}
      - PORT=3030
    restart: unless-stopped 

  mongodb:
    image: mongo:7.0  # 使用官方MongoDB镜像，推荐指定版本
    restart:  unless-stopped 
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    ports:
      - '80:80' # 对外暴露80端口
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # 挂载配置文件
    depends_on:
      - nuxt-app # 确保nuxt先启动
    restart: unless-stopped # 推荐策略

volumes:
  mongodb_data:
  redis_data: