version: "3.8"

services: 
  nuxt-app:
    build: ./website
    ports:
      - '3000:3000'
    depends_on:
      - express
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped 

  express:
    build: ./server
    ports:
      - '3030:3030'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped 